name: Update Main from Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v3
        with:
          ref: staging

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          title: 'Update main from staging'
          body: |
            This pull request updates the `main` branch with the latest changes from the `staging` branch.
