name: Create production promotion pull request
on:
  push:
    branches:
      - staging
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git checkout -- Dockerfile .github/workflows/*
          git reset HEAD Dockerfile .github/workflows/*
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: staging-promotion
