name: PR test

on:
  push:
    branches:
      - staging
  workflow_dispatch: # Allows manual triggering

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Staging Branch
      uses: actions/checkout@v3
      with:
        ref: staging

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Sync staging to main"
        branch: "staging"
        base: "main"
        title: "Sync Staging to main"
        body: "This PR merges changes from the staging branch into the main branch."
        labels: "auto-sync"
