name: test
on:
  push:
    branches:
      - staging
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin staging
          git reset --hard staging
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: staging-main-sync
