name: Sync staging branch to main
on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  syncStagingToMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin staging:staging
          git reset --hard staging
      - name: Restore our version of Dockerfile
        run: |
          git checkout main -- Dockerfile
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: sync-staging-to-main
